services:
  localstack:
    image: localstack/localstack:4.10.0
    container_name: localstack-image-svc
    ports:
      - "4566:4566" # Edge port for all AWS services
    environment:
      SERVICES: lambda,s3,dynamodb,apigateway,sqs
      DEBUG: 1
      PERSISTENCE: 1
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - './localstack-data:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock' # needed for Lambda, etc.
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:4566/_localstack/health | grep 'running'"]
      interval: 5s
      timeout: 10s
      retries: 10
  tests:
    build:
      context: .
      dockerfile: docker-test.Dockerfile
    container_name: image-service-tests
    volumes:
      - ./:/app:cached
    environment:
      - PYTHONPATH=/app/src
    tty: false
    stdin_open: false
